# Generated by Django 3.1.4 on 2020-12-15 09:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_compress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Закодированное изображение', 'verbose_name_plural': 'Закодированные изображения'},
        ),
        migrations.AlterField(
            model_name='data',
            name='array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=500, verbose_name='Данные'),
        ),
    ]
