# Generated by Django 3.1.4 on 2020-12-16 17:02

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image_compress', '0002_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=500, verbose_name='Данные'),
        ),
        migrations.AlterField(
            model_name='image',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
